/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mp4_escape_to_pokagon_package;

import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author m-babej
 */
public class CompassLabel extends JLabel {

    /**
     * Creates new form DieLabel
     */
    private ImageIcon[] compassImage        = new ImageIcon[ 5 ];

    public CompassLabel() {
        initComponents();
        for ( int i = 0; i < 5; i++ ) {
            String filename = "/images/compass" + i + ".png";
            compassImage[i]     = new ImageIcon( this.getClass().getResource(filename) );
        }
    }
    
    public void setImage(int i) {
        this.setIcon( compassImage[i]); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compass0.png"))); // NOI18N
        setText("WEST");
        setVerticalAlignment(javax.swing.SwingConstants.TOP);
        setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        setMaximumSize(new java.awt.Dimension(80, 100));
        setMinimumSize(new java.awt.Dimension(80, 100));
        setPreferredSize(new java.awt.Dimension(210, 250));
        setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
