/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mp4_escape_to_pokagon_package;

import javax.swing.*;

/**
 *
 * @author m-babej
 */
public class CompassLabel extends JLabel {

    /**
     * Creates new form DieLabel
     */
    private ImageIcon[] compassImage = new ImageIcon[ 15 ];

    public CompassLabel() {
        initComponents();
        for ( int i = 0; i < 15; i++ ) {    //iterate through ImageIcons, initializing with the filenames of images representing every possible combo of directions (N, E, S, W)
            String filename = "/images/compass" + i + ".png";
            compassImage[i] = new ImageIcon( this.getClass().getResource(filename) ); 
        }
    }
    
    /**
     *Sets this labels text to the displayed directions
     * @param i  //the number corresponding to the displayed directions
     */
    public void setImage(int i) {
        String direction = "";
        this.setIcon( compassImage[i]);
        switch(i) {
            case 0: direction = "North";
                break;
            case 1: direction = "East";
                break;
            case 2: direction = "South";
                break;
            case 3: direction = "West";
                break;
            case 4: direction = "North, East";
                break;
            case 5: direction = "East, South";
                break;
            case 6: direction = "South, West";
                break;
            case 7: direction = "North, West ";
                break;
            case 8: direction = "East, West";
                break;
            case 9: direction = "North, South";
                break;
            case 10: direction = "North, East, South";
                break;
            case 11: direction = "East, South, West";
                break;
            case 12: direction = "North, South, West";
                break;
            case 13: direction = "North, East, West";
                break;
            case 14: direction = "North, East, South, West";
                break;
        }
        this.setText(direction);
    }

    /**
     *Sets the appropriate img to represent the directions given as parameters
     * @param north boolean representing the direction north
     * @param east boolean representing the direction east
     * @param south boolean representing the direction south
     * @param west boolean representing the direction west
     */
    public void showDirections(boolean north, boolean east, boolean south, boolean west) {
        int imgNum = 0;  //var holding the value that selects the appropriate img
        if(north)
            imgNum = 0;
         if(east)
            imgNum = 1;
         if(south)
            imgNum = 2;
         if(west)
            imgNum = 3;
         if(north && east)
            imgNum = 4;
         if(east && south)
            imgNum = 5;
         if(south && west)
            imgNum = 6;
         if(west && north)
            imgNum = 7;
         if(east && west)
            imgNum = 8;
         if(north && south)
            imgNum = 9;
         if(north && east && south)
            imgNum = 10;
         if(east && south && west)
            imgNum = 11;
         if(south && west && north)
            imgNum = 12;
         if(west && north && east)
            imgNum = 13;
        if(north && east && south && west)
            imgNum = 14;
        setImage(imgNum);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compass0.png"))); // NOI18N
        setText("North");
        setVerticalAlignment(javax.swing.SwingConstants.TOP);
        setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        setMaximumSize(new java.awt.Dimension(80, 100));
        setMinimumSize(new java.awt.Dimension(80, 100));
        setPreferredSize(new java.awt.Dimension(210, 250));
        setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}